name: QA Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright
        run: playwright install --with-deps chromium

      - name: Run tests
        working-directory: reqres-api/swag_labs_ui/pages
        run: pytest